[package]
name = "mqttclinet"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["clock", "std", "serde"] }
dotenvy = "0.15.7"
mongodb = "2.8.2"
rumqttc = "0.24.0"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
